# -*- coding: utf-8 -*-
"""TareaCsvFile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DJlI4Wze8IcyRXKYCwz8wvEsdDy9uAf
"""

import pandas as pd

csvFile='/content/file.csv'

df=pd.read_csv(csvFile)

print(df)

